# An Introduction to Basic Julia Functionality 

# What is a vector?
    a vector is a one dimensional array.  It is like one row or column in a spreadsheet, and can hold any kind of data

How do we build one?

In [7]:
[1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

In [8]:
[1,2,3,4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [9]:
 ["dog", "cat", "bird", "mouse"]

4-element Array{String,1}:
 "dog"
 "cat"
 "bird"
 "mouse"

To declare a vector in Julia, use the square braces []

A ROW vector has items separated by spaces

A COLUMN vector has items separated by commas


Lets say that you build a vector full of animals

animalsVector =  ["dog", "cat", "bird", "mouse"]

Notice: by giving this vector a title, we have saved it in the computer's memory

If I want to take out just the bird, I have to do INDEXING
Each entry of the vector has a number label of its position, aka an Index

In [11]:
animalsVector =  ["dog", "cat", "bird", "mouse"]
#lets find the cat!  
#you can index into a vector with the position inside square braces
animalsVector[2]

"cat"

A word of Warning! Indexing out of bounds will cause an error!

In [12]:
vectorFourLong = [1 2 3 4]
vectorFourLong[5]

BoundsError: BoundsError: attempt to access 1×4 Array{Int64,2} at index [5]

# What is a Matrix?
    a matrix is a two dimensional array.  It is like a bunch of row vectors stacked on top of each other

Matrices are built just like vectors.
Use a semicolon to indicate a new row!

In [15]:
["a" "b" "c" "d"; "e" "f" "g" "h"]

2×4 Array{String,2}:
 "a"  "b"  "c"  "d"
 "e"  "f"  "g"  "h"

Indexing into matrices works just like vectors, but you now need two coordinates.
Index with the format [row, column] 

In [16]:
myMatrix = ["a" "b" "c" "d"; "e" "f" "g" "h"]
myMatrix[2,3]

"g"

You can also slice a matrix into rows or columns by using the : operator during indexing

In [17]:
myMatrix = ["a" "b" "c" "d"; "e" "f" "g" "h"]
myMatrix[2,:]
#this operation will extract all of row 2

4-element Array{String,1}:
 "e"
 "f"
 "g"
 "h"

# Other ways to build an array/matrix

Range Notation:
Use a colon to create a vector or matrix with a range of values

In [11]:
[1:10; 21:30]

20-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30

Build now, fill later with
Array{T}(undef, dims)
Where T is the type
and dims is the dimensions
Note: for concrete types, julia will automatically fill in the matrix with junk values

In [18]:
Array{Int64}(undef, 2, 3)

2×3 Array{Int64,2}:
 368363696  368363728  158578320
 156449200  157065840  163143984

In [6]:
#You can put the correct values in by indexing
junkArray = Array{Int64}(undef, 2, 3)
junkArray[1, 2] = 18;
junkArray[2, 3] = 45;
junkArray[2, 1] = 6;
junkArray

2×3 Array{Int64,2}:
 344327936         18  344327952
         6  140148768         45

There are some built-ins for quick matrix building:

**zeros(T, dims)
ones(T, dims)**

Both of these functions build a matrix full of either ones or zeros, with specified dimensions

# When is this useful?
